config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
  
  resources :users do
    resources :posts do
      resources :comments, :likes
    end
  end

  # add routes for api endpoints
  namespace :api do
    resources :users do
      resources :posts do
        resources :comments
    end
  end
end
end

  

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.admin?
      can :manage, :all
    else
      can :read, :all
      can :create, Post, :all
      can :destroy, Post, author_id: user.id
      can :create, Comment, :all
      can :destroy, Comment, author_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, class_name: 'Post'

  after_save :update_comment_counter
  after_destroy :update_comment_counter

  def update_comment_counter
    post.update(comments_counter: post.comments.count)
  end

  def as_json(options = {})
    super({ only: %i[text author_id post_id] }.merge(options))
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, class_name: 'Post'

  after_save :update_likes_counter

  def update_likes_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, foreign_key: 'post_id', dependent: :destroy
  has_many :likes, foreign_key: 'post_id', dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_post_counter
  after_destroy :update_post_counter

  def newest_comments
    comments.order(created_at: :desc).limit(5)
  end

  def update_post_counter
    author.update(posts_counter: author.posts.count)
  end

  def as_json(options = {})
    super({ only: %i[title text] }.merge(options))
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true, length: { maximum: 250 }
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def newest_posts
    posts.order(created_at: :desc).limit(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @post = Post.find(request.params['post_id'])
    render json: @post.comments.all
  end

  def create
    comment_params = params.require(:comment).permit(:author_id, :post_id, :text)
    @user = User.find(comment_params[:author_id])
    @post = Post.find(comment_params[:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.author_id = @user.id
    @comment.post_id = @post.id
    puts @comment
    if @comment.save
      render json: { status: 'created succesfully' }
    else
      render json: { status: 'ouch!' }
    end
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  def index
    @user = User.find(request.params['user_id'])
    render json: @user.posts.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:email, :encrypted_password)
    end

    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:name, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    @comment.post = @user.posts.find(params['post_id'])
    respond_to do |format|
      if @comment.save
        format.html { redirect_to user_posts_path(@user) }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to user_posts_path(current_user), notice: 'Comment destroyed successfully' }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @like = Like.new(like_params)
    @like.author_id = current_user.id
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) } if @like.save
    end
  end

  private

  def like_params
    params.permit(:author_id, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:author, :comments)
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def destroy
    @post = Post.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to user_posts_path(current_user), notice: 'Post destroyed successfully' }
    end
  end

  def create
    @post = current_user.posts.new(post_params)
    @post.author_id = current_user.id
    @post.comments_counter = 0
    @post.likes_counter = 0

    respond_to do |format|
      if @post.save
        format.html { redirect_to user_posts_path(current_user) }
      else
        format.html { render :new }
      end
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/api/comments_helper.rb
module Api::CommentsHelper
end

app/helpers/api/posts_helper.rb
module Api::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<div id="container">
<div class="form"
<h3>ADD NEW COMMENT</h3>

<br>
<br>


<%= form_with model: @comment, url: user_post_comments_path do |form| %>
  <div class="form-cont">
    <div class="form-field">
           <%= form.text_area :text, required: true, :class => 'form-text-area' %>
    </div>
<br>
    <%= form.submit %>
  </div>
<% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

   <body>

        <div id = "container">
         
      
         <div id = "content">
          <%= yield -%>
         </div>

           
      </div>
      <p class="notice"><%=notice%> </p>
      <p class="alert"><%=alert%> </p> 
      
   </body>
   
</html>

app/views/layouts/standard.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns = "http://www.w3.org/1999/xhtml">

   <head>
      <meta http-equiv = "Content-Type" content = "text/html; charset = iso-8859-1" />
      <meta http-equiv = "Content-Language" content = "en-us" />
      <title>Blog App</title>
      <%= stylesheet_link_tag "application" %>
   </head>

   <body>
      <div id = "container">
         
      
         <div id = "content">
            <%= yield -%>
         </div>

               
      </div>
   </body>
   
</html>

app/views/partials/_user_info.html.erb
<div class="user_container">
    <img class="user_image" src="<%= user.photo ? user.photo : 'https://reputationtoday.in/wp-content/uploads/2019/11/110-1102775_download-empty-profile-hd-png-download.jpg' %>">
    <ul class="user_info">
            <li class="name"><%= user.name %></li>
            <li class="user_posts">Number of posts: <%= user.posts_counter %></li>
    </ul>
</div>

app/views/posts/index.html.erb
<div id="container">
<%= render('partials/user_info', user: @user) %>
<div class="user_container">
<%= link_to new_user_post_path(@user) do %>
<button class="add-post">Add New Post</button>
<% end %>
</div>
<div class="posts-container">
  <% @posts.each do |post| %>
    <div class="post-and-comments">
        <div class="post">
        <h4><%=link_to "Post #{post.id}", user_post_path(@user, post)  %></h4>
          <p><%= post.text %></p>
          <%if can? :destroy, post %>
          <%= button_to "Delete Post", user_post_path(post.author,post), method: :delete, data: { turbo_confirm: "Are you sure?" }  %>
          <% end %>
        </div>
        <% if post.comments.length.positive? %>
        <div class="comments">
            <% post.newest_comments.each do |comment| %>
              <p><%= comment.id %>. <%= comment.text %></p>
              <%if can? :destroy, comment %>
              <%= button_to "Delete Comment", user_post_comment_path(comment.author_id, comment.post_id, comment), method: :delete, data: { turbo_confirm: "Are you sure?" }  %>
              <% end %>
            <% end %> 
        </div>
      <% end %>
    </div>
  <% end %>
  <div class="pagination">
  <button class="b_posts">Pagination</button>
</div>
</div>
</div>

app/views/posts/new.html.erb
<div id="container">
<div class="form"
<h3>ADD NEW POST</h3>

<br>
<br>

<%= form_with model: @post, url:user_posts_path do |form| %>
  <div class="form-cont">
    <div class="form-field">
    <%= form.label :title, :class => 'form-title' %> 
    <%= form.text_field :title, :class=>'form-text-field' %>
    <br>
  
    <%= form.label :text, :class => 'form-text' %>
    <%= form.text_area :text, required: true, :class => 'form-text-area' %>
    </div>
<br>
    <%= form.submit "Add post" %>
  </div>
<% end %>
</div>
</div>

app/views/posts/show.html.erb
<div id="container">
  <div class="post_info">
  <div class="post_top">
    <h4>Post #<%= @post.id %> by <%= @user.name %></h4>
    <p class='post-counters'>Comments <%= @post.comments_counter %>, Likes <%= @post.likes_counter %></p>
    </div>
    <p class='post-text'><%= @post.text %></p>
  </div>
  
  <% if @post.comments.length.positive? %>
    <div class="comments">
        <% @post.comments.each do |comment| %>
          <p><%= comment.author.name %>: <%= comment.text %></p>
        <% end %>
    </div>
  <% end %>

<div class="comment-like">
<%= link_to new_user_post_comment_path(@user, @post) do %>
<button class="add-post">Add New Comment</button>
<% end %>

<%= form_with model: Like.new, url: user_post_likes_path(@user, @post) do |form| %>
  <% form.submit "Add Like", class: "add-like" %>
<% end %>
 
  </div>

</div>

app/views/users/index.html.erb
<ul>
<% @users.order(id: :asc).each do |user| %>
   <li> 
   <%= link_to(render('partials/user_info', user: user), user_path(user)) %>
   </li>
    <% end %>

</ul>

app/views/users/show.html.erb
    
    <%= render "partials/user_info", user: @user %>
    <%= link_to root_path do %>
      <button class="b-home">Home</button>
      <% end %>
    <div class="user_details">
    <p><span>Bio <br><br></span><%= @user.bio %></p>
    </div>
  <% @user.newest_posts.each do |post| %>
    <div class="post">
      <h4>Post #<%= post.id %></h4>
      <p><%= post.text %></p>
    </div>
  <% end %>
  <div class="see_all_posts">
  <button class="b_posts"><%= link_to('See all posts', user_posts_path(@user)) %></button>
</div>